version: '3.3'

# Define environment variables (.env) where ${variable}

services:

  traefik:
    image: traefik:v2.9
    restart: always
    container_name: traefik
    command:
      #- "--log.level=ERROR"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=${MY_EMAIL}" # Place your email here
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      #- "8080:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${exampleuser}
      WORDPRESS_DB_PASSWORD: ${examplepass}
      WORDPRESS_DB_NAME: ${exampledb}
    volumes:
      - wordpress:/var/www/html
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.wordpress.entrypoints=websecure'
      - 'traefik.http.routers.wordpress.rule=Host("${MYDOMAIN}")' # Place your right domain here
      - 'traefik.http.routers.wordpress.tls=true'
      - 'traefik.http.routers.wordpress.tls.certresolver=myresolver'
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${exampledb}
      MYSQL_USER: ${exampleuser}
      MYSQL_PASSWORD: ${examplepass}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    labels:
      - 'traefik.enable=false'

volumes:
  wordpress:
  db:
  traefik-ssl-certs:
    driver: local
